package com.kiran.casemanagement.enums;

public enum AuditAction {
    REQUEST_CREATED,
    AI_CLASSIFICATION_GENERATED,
    AI_CLASSIFICATION_FAILED,
    AI_SUMMARY_GENERATED,
    AI_SUMMARY_FAILED,
    CASE_ASSIGNED,
    STATUS_CHANGED,
    NOTE_ADDED,
    PRIORITY_CHANGED,
    CASE_RESOLVED,
    CASE_REOPENED,
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DEACTIVATED
}
